name: Deploy to NuGet

on:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check Git version
        run: git --version


      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Check for changes
        id: check_changes
        run: |
          $CHANGED_PROJECTS = git diff --name-only 9649dd1ab9df5565653333bde4124253ad40af1d...e5277989780df641fb67aa7f2c1c4230e0079b0f '*.csproj' | %{ $_.Split('/')[0] } | sort -u
          echo "::set-output name=changed_projects::$CHANGED_PROJECTS"
        shell: pwsh


      - name: 'Restore packages'
        run: dotnet restore

      - name: 'Build project'
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build

      - name: 'Pack project'
        run: |
          for project in ${{ steps.check_changes.outputs.changed_projects }}; do
            dotnet pack --no-build --output nupkg "$project"
          done

      - name: 'Push to NuGet'
        run: |
          for package in ./nupkg/*.nupkg; do
            dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          done

